### ISSUE TITLE
C#  public action method 'stylesheet' was not found on controller

### ISSUE THREAD

**Issue by jeffrockwell** [alexbeletsky/elmah-mvc#19]
I downloaded the latest elmah via nuget and have your latest source code that fixes issue 14 and 16. In my MVC app in C# i still get 'A public action method 'stylesheet' was not found on controller...' Very similar to the post a few months back when a VB programmer saw the same error.
thanks

**Comment by blbirajdar** [comment]
I am still facing the issue with latest 1.2.2 version as well. Is this issue still open ? I cant see a workaround for it.
