### ISSUE TITLE
Always getting 403

### ISSUE THREAD

**Issue by david-martyn-ford** [alexbeletsky/elmah-mvc#27]
I am always getting 403 - File access denied and I do not know why.

I setup the auth on and with the role and it works on my localhost but when pushed to my server it does not work.

**Comment by HughJeffner** [comment]
This is safe if you configure these correctly, right?

```
<add key="elmah.mvc.allowedRoles" value="*" />
<add key="elmah.mvc.allowedUsers" value="*" />
```
