### ISSUE TITLE
Required dependency of type Elmah.Mvc.ElmahController could not be resolved.

### ISSUE THREAD

**Issue by joeldow** [alexbeletsky/elmah-mvc#43]
Elmah was working in my project but suddenly started giving me this message.  I cannot get elmah working properly.  What should I do?  Elmah still stores data in the db, but doesn't give me a UI.

http://stackoverflow.com/questions/21152657/required-dependency-of-type-elmah-mvc-elmahcontroller-could-not-be-resolved

<error
  application="/LM/W3SVC/4/ROOT"
  host="JDOW-WIN7VM"
  type="Funq.ResolutionException"
  message="Required dependency of type Elmah.Mvc.ElmahController could not be resolved."
  source="ServiceStack"
  detail="Funq.ResolutionException: Required dependency of type Elmah.Mvc.ElmahController could not be resolved.&#xD;&#xA;   at Funq.Container.GetEntry[TService,TFunc](String serviceName, Boolean throwIfMissing)&#xD;&#xA;   at Funq.Container.ResolveImpl[TService](String name, Boolean throwIfMissing)&#xD;&#xA;   at lambda_method(Closure , Container )&#xD;&#xA;   at ServiceStack.ServiceHost.ContainerResolveCache.CreateInstance(Type type, Boolean tryResolve)&#xD;&#xA;   at ServiceStack.Mvc.FunqControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)&#xD;&#xA;   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)&#xD;&#xA;   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController&amp; controller, IControllerFactory&amp; factory)&#xD;&#xA;   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)&#xD;&#xA;   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()&#xD;&#xA;   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)"
  user="[user]"
  time="2014-01-22T23:11:35.5732170Z">

**Comment by issafram** [comment]
DI issue, not an ELMAH.MVC issue.

**Comment by darrenshrwd** [comment]
@sl33kr Does this mean that I can't use this package with servicestack and keep the servicestack Mvc-integration I have?

**Comment by sl33kr** [comment]
@darrenshrwd No it should still work. In our case because we weren't using Funq as our controller we had to use the FunqControllerFactory to instruct Funq/ServiceStack to lookup dependencies from our container. That constructor I gave the example for the first parameter is your container, next set is a param array of assemblies that ServiceStack should scan to look for MVC controllers.

**Comment by darrenshrwd** [comment]
Thanks, I can't find 'ElmahLogger' any more, but the following worked:
```
// Set MVC to use the same Funq IOC as ServiceStack, include the Elmah.Mvc assembly
ControllerBuilder.Current.SetControllerFactory(new FunqControllerFactory(container, typeof(Elmah.Mvc.ElmahController).GetAssembly())); 
```
HOWEVER I then tried setting the config key "elmah.mvc.requiresAuthentication" value to "true" I could no longer login to my site (uses ServiceStack authentication)...I expect to use the servicestack authentication I will need the ElmahController to inherit from ServiceStackController as then the IsAuthenticated will work.  I guess I will get the source for this repo and go from there, thanks.
