### ISSUE TITLE
Internal Server Error error code 500 is logged as 0

### ISSUE THREAD

**Issue by RehanSaeed** [alexbeletsky/elmah-mvc#61]
What steps will reproduce the problem?
1.Cause a 500 error in your site.
2.View the /elmah.axd page
3.View the error and the code column.
4.See that the error is logged with a code of zero instead of 500.

What is the expected output? What do you see instead?
You should see a 500 instead of zero.

Please use labels and text to provide additional information.
Comment #20 in the following issue talks about this bug but I have raised it as an issue to be addressed.
https://code.google.com/p/elmah/issues/detail?id=217

I have also raised this issue with Google Elmah <a href="https://code.google.com/p/elmah/issues/detail?id=390&thanks=390&ts=1428927559">here</a>.

**Comment by papci** [comment]
It's an elmah core bug. We have to wait for a fix.

**Comment by RehanSaeed** [comment]
Thanks for confirming. Lets wait and see if someone replies to the issue I raised.
