### ISSUE TITLE
Doesn't work with an oracle database

### ISSUE THREAD

**Issue by smillingrainbow** [alexbeletsky/elmah-mvc#65]
Hi, 
I have an asp.net mvc4 application and I'm looking to do the error handling with elmah.
I want to save my log in an oracle database so I ran the oracle.sql script from the source of elmah. But with this web.config(bellow), I can't acces to the elmah page with all the log and nothing is store into the database : 
```
<connectionStrings>
    <add name="elmah-oracle" connectionString="data source=****;password=******;user id=*****"/>
<\connectionStrings>
....
<elmah>
    <errorLog type="Elmah.OracleErrorLog, Elmah" connectionStringName="elmah-oracle" />
<\elmah>
```
And also, everything works fine if I'm using xml files as storage. 
Thanks for your help

**Comment by papci** [comment]
Hi,

This is an elmah core issue. You can submit your report here : https://code.google.com/p/elmah/issues/list

**Comment by smillingrainbow** [comment]
Yeah I did it. I just have to wait for an answer now. Thanks
