### ISSUE TITLE
Allow OracleErrorLog to use Oracle.ManagedDataAccess

### ISSUE THREAD

**Issue by bogile** [alexbeletsky/elmah-mvc#74]
I just updated my web application based on an oracle database to use the Oracle.ManagedDataAccess. Now I don't have to install the oracle client on every development machine as well as on every other server, that I want to run my system on. The only thing missing is that Elmah is able to connect through this Oracle.ManagedDataAccess. I have tried to look at the code to see, if I could do some refactoring myself, but I could not find the correct location to make the changes.

**Comment by issafram** [comment]
This sounds like an ELMAH issue and not an ELMAH.MVC issue.
