### ISSUE TITLE
Mention license

### ISSUE THREAD

**Issue by yesman85** [alexbeletsky/elmah-mvc#76]
Hello,

could you add a quick mention of a license somewhere? Now it just looks like it doesn't have one at all. Which restricts usage quite a bit!

Thanks

**Comment by issafram** [comment]
There is a license over here: https://github.com/alexbeletsky/elmah-mvc/blob/master/COPYING.txt

Got it?

**Comment by yesman85** [comment]
Oh yeah, didn't even see that, sorry!
